# encoding: utf-8
# Site settings
title: {{ site.data.branding.site_name }}
email: {{ site.data.branding.email }}
description: {{ site.data.branding.tagline }}
baseurl: "" # the subpath of your site, e.g. /blog
url: 'https://hasmerch.com'
twitter_username: {{ site.data.branding.twitter }}
github_username:  {{ site.data.branding.github }}

# Build settings
plugins:
  - jekyll-feed
feed:
  icon: "icon"
  logo: "logo"
collections:
  products:
    output: true
sass:
  sass_dir: assets/css
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
