# Site settings
title: Merch
email: prod.cxxl@gmail.com
description: >
  Merch for you, Made by CXXL
baseurl: '/merch'
url: 'https://prod-cxxl.github.io/'
twitter_username: prod.cxxl
github_username:  prod.cxxl

# Build settings
plugins:
  - jekyll-feed
feed:
  icon: /images/LogoBG.png
  logo: /images/LogoFull.JPG
collections:
  products:
    output: true
 
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/